---
- name: chezmoi ~> get current install stat
  stat:
    path: "{{ chezmoi_bin }}"
  register: reg_chezmoi

- name: chezmoi ~> install
  include_tasks: install.yml
  when: not reg_chezmoi.stat.exists
