---
name: CI
on:
  push:
    branches: [main]
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: 'kilip.chezmoi'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: kilip.chezmoi

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
          cache: pip

      - name: Install test dependencies.
        run: pip3 install yamllint

      - name: Lint code.
        run: |
          yamllint .
  molecule:
    name: Molecule (${{ matrix.distro }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        distro:
          - centos-8
          #- centos-7
          - ubuntu-22.04
          #- ubuntu-20.04
          #- ubuntu-18.04
          - debian-11
          #- debian-10
          #- debian-9
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v3
        with:
          path: kilip.proxy

      - name: Set up Python 3.
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          cache: pip

      - name: Install test dependencies.
        run:
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Molecule tests.
        run: make test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DIST: ${{ matrix.distro }}
